# Generated by Django 5.2.7 on 2026-03-29 08:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total price for this line item (quantity × (base_price + modifier_prices)). Auto-calculated.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="core.restaurant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("OCCUPIED", "Occupied"),
                    ("NEEDS_CLEANING", "Needs Cleaning"),
                    ("RESERVED", "Reserved"),
                    ("MERGED", "Merged"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="table_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("restaurant", "table_number")},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant", "status"], name="core_order_restaur_fead6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="core_order_created_912d27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="core_orderi_order_i_b7b8d3_idx"),
        ),
    ]
