# Generated by Django 5.2.7 on 2025-11-02 06:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuvariant",
            options={
                "ordering": ["menu_item", "price_modifier"],
                "verbose_name": "Menu Variant",
                "verbose_name_plural": "Menu Variants",
            },
        ),
        migrations.AddField(
            model_name="menuitem",
            name="prep_time",
            field=models.DurationField(
                default=datetime.timedelta(seconds=600),
                help_text="Estimated preparation time for this item (e.g., 00:15:00 for 15 mins).",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Required. Used for login and notifications.",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="low_stock_threshold",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Threshold for low stock alerts.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="menuvariant",
            name="price_modifier",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount to add to the base price.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway_ref",
            field=models.CharField(
                blank=True,
                help_text="Reference ID from payment gateway.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="month",
            field=models.CharField(
                editable=False,
                help_text="Automatically generated for easy filtering.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="screendisplay",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="displays",
                to="core.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="coordinates",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional JSON for floor plan UI, e.g. {'x': 100, 'y': 50}",
            ),
        ),
        migrations.AddConstraint(
            model_name="menuitem",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "name"), name="unique_menu_item_per_restaurant"
            ),
        ),
    ]
