# Generated by Django 5.2.7 on 2025-11-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
