# Generated by Django 5.2.7 on 2026-04-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_order_notes_alter_customuser_phone_number_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PLACED", "Placed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("READY", "Ready"),
                    ("SERVED", "Served"),
                    ("CANCELED", "Canceled"),
                    ("COMPLETED", "Completed"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
