# Generated by Django 5.2.7 on 2025-11-20 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_menuitem_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "content",
                    models.TextField(help_text="Raw text of the chat message."),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("system_generated", models.BooleanField(default=False)),
                (
                    "important",
                    models.BooleanField(
                        default=False,
                        help_text="If marked, indicates this message was flagged as important in UI.",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        help_text="If applicable, scope message to a particular restaurant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="core.restaurant",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who sent the message (retained even if user is deleted).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="core_chatme_timesta_06a3e8_idx"
                    ),
                    models.Index(
                        fields=["restaurant", "timestamp"],
                        name="core_chatme_restaur_0f2862_idx",
                    ),
                ],
            },
        ),
    ]
