# Generated by Django 5.2.7 on 2025-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending", "Pending"),
                    ("cooking", "Cooking"),
                    ("ready", "Ready"),
                    ("served", "Served"),
                    ("paid", "Paid"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
