# Generated by Django 5.2.7 on 2026-04-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
