# Generated by Django 5.2.7 on 2025-11-21 13:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_table_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
