# Generated by Django 5.2.7 on 2026-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_order_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prep_time",
            field=models.PositiveIntegerField(
                default=10, help_text="Average preparation time in minutes"
            ),
        ),
    ]
