# Generated by Django 5.2.7 on 2025-11-22 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_orderitem_final_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={"ordering": ["restaurant", "table_number"]},
        ),
    ]
