# Generated by Django 5.2.7 on 2026-04-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="capacity",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
