# Generated by Django 5.2.7 on 2026-04-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_order_tip_waitercall"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
