# Generated by Django 5.2.7 on 2026-04-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_order_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
