# Generated by Django 5.2.7 on 2026-04-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_restaurant_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
