# Generated by Django 5.2.7 on 2026-04-18 13:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_restaurant_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenticket",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kitchenticket",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kitchenticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("PREPARING", "Preparing"),
                    ("COMPLETED", "Completed"),
                ],
                default="QUEUED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddIndex(
            model_name="kitchenticket",
            index=models.Index(fields=["status"], name="core_kitche_status_7448d2_idx"),
        ),
        migrations.AddIndex(
            model_name="kitchenticket",
            index=models.Index(
                fields=["created_at"], name="core_kitche_created_b0886c_idx"
            ),
        ),
    ]
