# Generated by Django 5.2.7 on 2026-04-19 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_tablesession_tablesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.tablesession",
            ),
        ),
    ]
