# Generated by Django 5.2.7 on 2026-04-19 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_order_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer_session",
        ),
        migrations.RemoveField(
            model_name="order",
            name="stripe_payment_intent_id",
        ),
        migrations.AddField(
            model_name="order",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.tablesection",
            ),
        ),
        migrations.AddField(
            model_name="tablesession",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="core.tablesection",
            ),
        ),
        migrations.DeleteModel(
            name="OrderStatusHistory",
        ),
    ]
