# Generated by Django 5.2.7 on 2026-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_order_created_by"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="core_order_created_912d27_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant", "created_at"],
                name="core_order_restaur_842692_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant", "payment_status"],
                name="core_order_restaur_144da1_idx",
            ),
        ),
    ]
