# Generated by Django 5.2.7 on 2026-05-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_order_core_order_created_912d27_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modifieroption",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifier_groups",
                to="core.restaurant",
            ),
        ),
    ]
