# Generated by Django 5.2.7 on 2026-05-04 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_modifieroption_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modifieroption",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifier_groups",
                to="core.restaurant",
            ),
        ),
    ]
