# Generated by Django 5.2.7 on 2026-05-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_modifieroption_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modifieroption",
            name="restaurant",
        ),
    ]
