# Generated by Django 5.2.7 on 2026-07-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_orderitem_variant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=100)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.restaurant",
                    ),
                ),
            ],
        ),
    ]
