# Generated by Django 5.2.7 on 2026-07-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_platform_owner",
            field=models.BooleanField(default=False),
        ),
    ]
