# Generated by Django 5.2.7 on 2026-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_customuser_is_platform_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablesession",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="tablesession",
            index=models.Index(
                fields=["table", "is_active"], name="core_tables_table_i_79223e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tablesession",
            index=models.Index(
                fields=["restaurant", "is_active"],
                name="core_tables_restaur_cc34e9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tablesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("table", "section"),
                name="unique_active_table_section_session",
            ),
        ),
    ]
