# Generated by Django 5.2.7 on 2026-07-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_tablesession_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Uncheck to hide this category from POS."
            ),
        ),
    ]
