# Generated by Django 5.2.7 on 2026-07-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_category_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="country",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
