# Generated by Django 5.2.7 on 2026-07-16 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_restaurant_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.tablesession",
            ),
        ),
    ]
