# Generated by Django 5.2.7 on 2026-07-16 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_order_session"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tablesession",
            name="unique_active_table_section_session",
        ),
        migrations.RemoveIndex(
            model_name="tablesession",
            name="core_tables_table_i_79223e_idx",
        ),
        migrations.AddField(
            model_name="tablesession",
            name="session_type",
            field=models.CharField(
                choices=[("TABLE", "Table"), ("TAKEAWAY", "Takeaway")],
                db_index=True,
                default="TABLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tablesession",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="core.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="tablesession",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="core.table",
            ),
        ),
        migrations.AddIndex(
            model_name="tablesession",
            index=models.Index(
                fields=["session_type", "is_active"],
                name="core_tables_session_01002e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tablesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("session_type", "TABLE")),
                fields=("table", "section"),
                name="unique_active_table_section_session",
            ),
        ),
    ]
