# Generated by Django 5.2.7 on 2026-07-16 19:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0030_remove_tablesession_unique_active_table_section_session_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tablesession",
            name="final_subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="tablesession",
            name="final_tax",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="tablesession",
            name="final_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
