# Generated by Django 5.2.7 on 2026-07-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_cashiershift_options_remove_refund_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="locale",
            field=models.CharField(
                default="en_US",
                help_text="Locale for formatting (e.g., en_US, de_DE, fr_FR)",
                max_length=10,
            ),
        ),
    ]
