# Generated by Django 5.2.7 on 2026-07-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_plan_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
