# Generated by Django 5.2.7 on 2026-08-01 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_alter_subscription_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loyaltytier",
            options={"ordering": ["-min_points"]},
        ),
        migrations.RenameField(
            model_name="loyaltytier",
            old_name="points_required",
            new_name="min_points",
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="customer",
            name="current_tier",
        ),
        migrations.AddField(
            model_name="loyaltytier",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loyalty_tiers",
                to="core.restaurant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="fee_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Processing fee percentage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="requires_reference",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to="core.restaurant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="loyaltytier",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount paid for this transaction.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="core.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="loyaltytier",
            unique_together={("restaurant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("restaurant", "name")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["order"], name="core_paymen_order_i_d56eb7_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="core_paymen_status_8390cc_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["stripe_payment_intent"], name="core_paymen_stripe__334442_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "table_number"),
                name="unique_table_number_per_restaurant",
            ),
        ),
    ]
