# Generated by Django 5.2.7 on 2026-08-04 02:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_loyaltytier_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="display_key",
            field=models.CharField(
                default=core.models.generate_display_key,
                max_length=64,
                null=True,   # ✅ changed
            ),
        ),
    ]