# Generated by Django 5.2.7 on 2026-08-04 02:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_restaurant_display_key"),
    ]

    operations = []
