# Generated by Django 5.2.7 on 2026-08-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_make_display_key_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "printer_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("KITCHEN", "Kitchen"),
                            ("DRINKS", "Drinks"),
                            ("GENERAL", "General"),
                        ],
                        default="RECEIPT",
                        max_length=30,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("NETWORK", "Network"),
                            ("USB", "USB"),
                            ("SYSTEM", "System Printer"),
                        ],
                        default="NETWORK",
                        max_length=30,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=9100,
                        help_text="Default port for many network thermal printers.",
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        blank=True,
                        help_text="Printer name installed on the operating system.",
                        max_length=255,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["printer_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("BILL", "Bill"),
                            ("RECEIPT", "Receipt"),
                            ("KITCHEN", "Kitchen Ticket"),
                            ("DRINKS", "Drinks Ticket"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PRINTING", "Printing"),
                            ("PRINTED", "Printed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_jobs",
                        to="core.order",
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to="core.printer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
