# Generated by Django 5.2.7 on 2026-08-06 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_printer_printjob"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="subscription",
            name="core_subscr_stripe__4e5b3f_idx",
        ),
        migrations.RemoveIndex(
            model_name="subscription",
            name="core_subscr_stripe__0ec66c_idx",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="cancel_at_period_end",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="stripe_subscription_id",
        ),
        migrations.AddField(
            model_name="plan",
            name="code",
            field=models.SlugField(
                blank=True,
                help_text="Internal plan code, e.g. starter, pro, enterprise",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="IANA timezone name, e.g. UTC, Europe/London, Africa/Banjul",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_reactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="offline_payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("mobile_money", "Mobile Money"),
                    ("cheque", "Cheque"),
                    ("other", "Other Offline Agreement"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="offline_payment_notes",
            field=models.TextField(
                blank=True, help_text="Notes about cash payment or offline agreement."
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="offline_payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Cash receipt number, transfer reference, or offline agreement reference.",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="reactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reactivated_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("CAD", "Canadian Dollar ($)"),
                    ("AUD", "Australian Dollar ($)"),
                    ("HKD", "Hong Kong Dollar (HK$)"),
                    ("TRY", "Turkish Lira (₺)"),
                    ("NGN", "Nigerian Naira (₦)"),
                    ("GMD", "Gambian Dalasi (D)"),
                    ("INR", "Indian Rupee (₹)"),
                    ("JPY", "Japanese Yen (¥)"),
                    ("CNY", "Chinese Yuan (¥)"),
                    ("ZAR", "South African Rand (R)"),
                    ("AED", "UAE Dirham (د.إ)"),
                    ("SAR", "Saudi Riyal (﷼)"),
                    ("SEK", "Swedish Krona (kr)"),
                    ("NOK", "Norwegian Krone (kr)"),
                    ("DKK", "Danish Krone (kr)"),
                    ("CHF", "Swiss Franc (CHF)"),
                    ("SGD", "Singapore Dollar (S$)"),
                    ("BRL", "Brazilian Real (R$)"),
                    ("MXN", "Mexican Peso ($)"),
                    ("KES", "Kenyan Shilling (KSh)"),
                    ("RWF", "Rwandan Franc (FRw)"),
                ],
                default="USD",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="locale",
            field=models.CharField(
                default="en_US",
                help_text="Locale for formatting, e.g. en_US, de_DE, fr_FR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("suspended", "Suspended"),
                    ("canceled", "Canceled"),
                ],
                default="trialing",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="core_subscr_status_deb962_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["current_period_end"], name="core_subscr_current_d45cf4_idx"
            ),
        ),
    ]
