# Generated by Django 5.2.7 on 2026-08-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_remove_subscription_core_subscr_stripe__4e5b3f_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="code",
            field=models.SlugField(
                help_text="Internal plan code, e.g. starter, pro, enterprise",
                max_length=100,
                unique=True,
            ),
        ),
    ]
