# Generated by Django 5.2.7 on 2026-08-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_alter_plan_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printer",
            options={"ordering": ["restaurant", "role", "name"]},
        ),
        migrations.RenameField(
            model_name="printjob",
            old_name="attempt_count",
            new_name="attempts",
        ),
        migrations.RemoveField(
            model_name="printer",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="printer",
            name="printer_type",
        ),
        migrations.RemoveField(
            model_name="printjob",
            name="order",
        ),
        migrations.AddField(
            model_name="printer",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="printer",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="printers",
                to="core.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="role",
            field=models.CharField(
                choices=[
                    ("KITCHEN", "Kitchen Printer"),
                    ("CASHIER", "Cashier/POS Printer"),
                ],
                default="KITCHEN",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printer",
            name="usb_product_id",
            field=models.CharField(
                blank=True, help_text="Optional USB product ID.", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="usb_vendor_id",
            field=models.CharField(
                blank=True, help_text="Optional USB vendor ID.", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="printjob",
            name="copies",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="printjob",
            name="max_attempts",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="printjob",
            name="raw_text",
            field=models.TextField(
                blank=True, help_text="Formatted text to send directly to printer."
            ),
        ),
        migrations.AddField(
            model_name="printjob",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="print_jobs",
                to="core.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="printjob",
            name="title",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="printer",
            name="connection_type",
            field=models.CharField(
                choices=[
                    ("NETWORK", "Network/IP"),
                    ("USB", "USB"),
                    ("SYSTEM", "System Printer"),
                ],
                default="NETWORK",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="Required for network/IP printers.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="port",
            field=models.PositiveIntegerField(
                default=9100,
                help_text="Default ESC/POS network printer port is usually 9100.",
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="system_name",
            field=models.CharField(
                blank=True,
                help_text="Operating system printer name, if using system printing.",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="job_type",
            field=models.CharField(
                choices=[("KITCHEN_ORDER", "Kitchen Order"), ("RECEIPT", "Receipt")],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured print data such as order items, totals, table, and waiter.",
            ),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("PRINTED", "Printed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="printer",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "name"), name="unique_printer_name_per_restaurant"
            ),
        ),
        migrations.AddConstraint(
            model_name="printer",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "role"), name="unique_printer_role_per_restaurant"
            ),
        ),
    ]
