# Generated by Django 5.2.7 on 2026-08-07 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_alter_printer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="printers",
                to="core.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="print_jobs",
                to="core.restaurant",
            ),
        ),
    ]
