# Generated by Django 5.2.7 on 2026-08-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_company_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="auto_print_kitchen_tickets",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="business_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="business_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="business_phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="default_order_type",
            field=models.CharField(
                choices=[
                    ("DINE_IN", "Dine In"),
                    ("TAKEAWAY", "Takeaway"),
                    ("DELIVERY", "Delivery"),
                ],
                default="DINE_IN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="receipt_header_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="require_table_for_dine_in",
            field=models.BooleanField(default=True),
        ),
    ]
