# Generated by Django 5.2.7 on 2026-08-21 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.AddField(
            model_name="customer",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="core.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="low_stock_threshold",
            field=models.IntegerField(default=0),
        ),
    ]
