# Generated by Django 5.2.7 on 2026-08-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_remove_customer_user_customer_restaurant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
    ]
