# Generated by Django 5.2.7 on 2026-08-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_customuser_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="code",
            field=models.SlugField(
                help_text="Internal plan code, e.g. starter, pro, enterprise.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="offline_payment_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="offline_payment_reference",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
