# Generated by Django 5.2.7 on 2026-08-26 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_alter_subscription_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_webhook_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "live_webhook_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "test_secret",
                    models.CharField(
                        default="713621027ca74cc58041f395d2dad4e8", max_length=64
                    ),
                ),
                (
                    "live_secret",
                    models.CharField(
                        default="06a05039c816455e90904d6f58ce1e53", max_length=64
                    ),
                ),
                (
                    "test_api_key",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "live_api_key",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("is_test_enabled", models.BooleanField(default=False)),
                ("is_live_enabled", models.BooleanField(default=False)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_config",
                        to="core.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=50, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                (
                    "environment",
                    models.CharField(
                        choices=[("TEST", "Test"), ("LIVE", "Live")], max_length=10
                    ),
                ),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.restaurant",
                    ),
                ),
            ],
        ),
    ]
