# Generated by Django 5.2.7 on 2026-08-26 21:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_webhookconfiguration_webhookevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookconfiguration",
            name="live_api_key",
            field=models.CharField(
                blank=True,
                default=django.utils.timezone.now,
                max_length=100,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="webhookconfiguration",
            name="live_secret",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="webhookconfiguration",
            name="live_webhook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="webhookconfiguration",
            name="test_api_key",
            field=models.CharField(
                blank=True,
                default=django.utils.timezone.now,
                max_length=100,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="webhookconfiguration",
            name="test_secret",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="webhookconfiguration",
            name="test_webhook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MenuItemIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_needed",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="How much of this inventory item is used for 1 serving of this Menu item",
                        max_digits=10,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_items",
                        to="core.inventoryitem",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="core.menu",
                    ),
                ),
            ],
        ),
    ]
