# Generated by Django 5.2.7 on 2026-09-02 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_required",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Amount of inventory item used for 1 unit of this product",
                        max_digits=10,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_products",
                        to="core.inventoryitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_recipe",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "inventory_item")},
            },
        ),
    ]
