# Generated by Django 5.2.7 on 2026-09-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_productingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="requires_reference",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
