# Generated by Django 5.2.7 on 2026-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_paymentmethod_requires_reference_paymentmethod_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="is_occupied",
            field=models.BooleanField(default=False),
        ),
    ]
