# Generated by Django 5.2.7 on 2026-09-13 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_order_payment_method"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentIntentLog",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="core_paymen_order_i_d56eb7_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="core_paymen_status_8390cc_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="core_paymen_stripe__334442_idx",
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="payment",
            name="stripe_payment_intent",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="restaurant",
        ),
    ]
