# Generated by Django 5.2.7 on 2026-09-13 09:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_delete_paymentintentlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.restaurant",
            ),
        ),
    ]
