# Generated by Django 5.2.7 on 2026-09-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_paymentmethod_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.restaurant",
            ),
        ),
    ]
