# Generated by Django 5.2.7 on 2026-09-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_alter_paymentmethod_restaurant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="core.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("mobile", "Mobile Payment"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to="core.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="slug",
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "name"),
                name="unique_payment_method_per_restaurant",
            ),
        ),
    ]
