# Generated by Django 5.2.7 on 2026-09-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_alter_paymentmethod_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={"ordering": ["restaurant_id", "table_number", "id"]},
        ),
        migrations.AlterModelOptions(
            name="tablesection",
            options={"ordering": ["table_id", "label"]},
        ),
        migrations.AlterModelOptions(
            name="tablesession",
            options={"ordering": ["-opened_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="tablesession",
            name="unique_active_table_section_session",
        ),
        migrations.RenameIndex(
            model_name="tablesession",
            new_name="session_restaurant_active_idx",
            old_name="core_tables_restaur_cc34e9_idx",
        ),
        migrations.RenameIndex(
            model_name="tablesession",
            new_name="session_type_active_idx",
            old_name="core_tables_session_01002e_idx",
        ),
        migrations.AlterUniqueTogether(
            name="tablesection",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="table",
            name="is_occupied",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("OCCUPIED", "Occupied"),
                    ("NEEDS_CLEANING", "Needs Cleaning"),
                    ("RESERVED", "Reserved"),
                    ("MERGED", "Merged"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tablesection",
            name="label",
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["restaurant", "status"], name="table_restaurant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["restaurant", "is_occupied"],
                name="table_restaurant_occupied_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tablesession",
            index=models.Index(
                fields=["table", "is_active"], name="session_table_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tablesection",
            constraint=models.UniqueConstraint(
                fields=("table", "label"), name="unique_section_label_per_table"
            ),
        ),
        migrations.AddConstraint(
            model_name="tablesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_active", True),
                    ("section__isnull", True),
                    ("session_type", "TABLE"),
                ),
                fields=("table",),
                name="unique_active_full_table_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="tablesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_active", True),
                    ("section__isnull", False),
                    ("session_type", "TABLE"),
                ),
                fields=("section",),
                name="unique_active_table_section_session",
            ),
        ),
    ]
