# Generated by Django 5.2.7 on 2026-09-22 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_alter_table_options_alter_tablesection_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="full_name",
            new_name="name",
        ),
    ]
