# Generated by Django 5.2.7 on 2026-10-06 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_rename_full_name_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="pending_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_subscriptions",
                to="core.plan",
            ),
        ),
    ]
