# --- Django Imports ---
from django.urls import path, include

# --- Third-Party Imports ---
from rest_framework.routers import DefaultRouter

# --- Local Application Imports ---
# Import the new, consolidated views
from .views import (
    # Authentication & Registration
    login_view,
    logout_view,
    RegisterView,
    
    # Core Dashboards & Static Views
    home,
    UserDashboardView,
    ManagerDashboardView,
    
    # Staff Management
    ClockInOutView,
    ShiftListView,
    ShiftCreateView,
    ShiftUpdateView,
    ShiftDeleteView,
    
    # Operational Views (KDS, Customer Display)
    KitchenDisplayView,
    CustomerDisplayView,
    pos_view,
    
    # API, AJAX & Data Export
    update_ticket_status,
    export_sales_data,
    
    # DRF Viewsets
    CustomUserViewSet,
    
    # Miscellaneous
    chat_room,
    inventory_list,

)

# ==============================================================================
# DJANGO REST FRAMEWORK ROUTER
# ==============================================================================
# The DRF router automatically generates URL patterns for ViewSets.
# This includes list, detail, create, update, and delete endpoints.
router = DefaultRouter()
router.register(r'users', CustomUserViewSet, basename='user')

# ==============================================================================
# URL PATTERNS
# ==============================================================================
app_name = 'core'

urlpatterns = [
    # --- Authentication ---
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    
    # --- Core & Dashboard Views ---
    path('', home, name='home'),
    path('dashboard/', UserDashboardView.as_view(), name='user_dashboard'),
    path('dashboard/manager/', ManagerDashboardView.as_view(), name='manager_dashboard'),
    
    # --- Staff Management ---
    # Single URL to handle both clocking in and out
    path('clock/', ClockInOutView.as_view(), name='clock'),
    
    # CRUD operations for Shifts, grouped under a 'shifts/' prefix
    path('shifts/', ShiftListView.as_view(), name='manage_shifts'),
    path('shifts/add/', ShiftCreateView.as_view(), name='add_shift'),
    path('shifts/<int:pk>/edit/', ShiftUpdateView.as_view(), name='edit_shift'),
    path('shifts/<int:pk>/delete/', ShiftDeleteView.as_view(), name='delete_shift'),

    # --- Operational Views ---
    path('kds/', KitchenDisplayView.as_view(), name='kds'),
    path('customer-display/', CustomerDisplayView.as_view(), name='customer_display'),
    
    # --- Miscellaneous Views ---
    path('chat/', chat_room, name='chat_room'),
    path('inventory/', inventory_list, name='inventory_list'),
    
    # --- API, AJAX & Data Export Endpoints ---
    # Include all URLs generated by the DRF router under the 'api/' prefix
    path('api/', include(router.urls)),
    
    # AJAX endpoint for the KDS to update ticket status
    path('ajax/update-ticket-status/<int:ticket_id>/', update_ticket_status, name='update_ticket_status'),
    
    # Data export endpoint
    path('export/sales/', export_sales_data, name='export_sales_data'),
    path('pos/', pos_view, name='pos'),

]